name: Documentation
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: doc

      - name: Checkout SPC
        uses: actions/checkout@v2
        with: 
          repository: damuellen/SPC
          token: ${{ secrets.MYPAT }}
          path: spc
          
      - name: Update package dependencies
        working-directory: ./spc
        run: swift package update
        
      - name: Build Debug mode
        working-directory: ./spc
        run: swift build -Xswiftc -suppress-warnings

      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: ".spc/Sources"
          module-name: BlackBoxModel
          minimum-access-level: internal
          output: "doc"
      
      - uses: actions/checkout@v2
      
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "doc"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.MYPAT }}
